import { FamilyMember } from './family-member';

export const FAMILYTREE: FamilyMember[] = [
  { id: 1, familyCode: '0', name: 'Carlos', surname1: 'Rey', surname2: 'Raviña', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 2, familyCode: '0.0', name: 'Filomena', surname1: 'Stolle', surname2: 'Lamela', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 3, familyCode: '1', name: 'María', surname1: 'Rey-Stolle', surname2: 'Raviña', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 7 },
  { id: 4, familyCode: '2', name: 'Josefa', surname1: 'Rey-Stolle', surname2: 'Raviña', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: false, offspring: 0 },
  { id: 5, familyCode: '3', name: 'Alejandro', surname1: 'Rey-Stolle', surname2: 'Raviña', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 16 },
  { id: 6, familyCode: '4', name: 'Carlos', surname1: 'Rey-Stolle', surname2: 'Raviña', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 7 },
  { id: 7, familyCode: '5', name: 'Nicasio', surname1: 'Rey-Stolle', surname2: 'Raviña', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 7 },
  { id: 8, familyCode: '1.0', name: 'José', surname1: 'del Río', surname2: 'Chico', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 7 },
  { id: 9, familyCode: '1.1', name: 'María Luisa', surname1: 'del Río', surname2: 'Rey-Stolle', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 10, familyCode: '1.2', name: 'Carlos', surname1: 'del Río', surname2: 'Rey-Stolle', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 11, familyCode: '1.3', name: 'José', surname1: 'del Río', surname2: 'Rey-Stolle', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 12, familyCode: '1.4', name: 'Mercedes', surname1: 'del Río', surname2: 'Rey-Stolle', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 13, familyCode: '1.5', name: 'Jesús', surname1: 'del Río', surname2: 'Rey-Stolle', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 14, familyCode: '1.6', name: 'María Carmela', surname1: 'del Río', surname2: 'Rey-Stolle', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 15, familyCode: '1.7', name: 'Alejandro', surname1: 'del Río', surname2: 'Rey-Stolle', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 5 },
  { id: 16, familyCode: '3.0', name: 'Mercedes', surname1: 'Pedrosa', surname2: 'Miranda', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 8 },
  { id: 17, familyCode: '3.0.1', name: 'María Rosa', surname1: 'de Imbert', surname2: 'Manero', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 18, familyCode: '3.1', name: 'Alejandro', surname1: 'Rey-Stolle', surname2: 'Pedrosa', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 19, familyCode: '3.2', name: 'José María', surname1: 'Rey-Stolle', surname2: 'Pedrosa', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 20, familyCode: '3.3', name: 'María Jacoba', surname1: 'Rey-Stolle', surname2: 'Pedrosa', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 21, familyCode: '3.4', name: 'Carlos María', surname1: 'Rey-Stolle', surname2: 'Pedrosa', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 22, familyCode: '3.5', name: 'Ignacio María', surname1: 'Rey-Stolle', surname2: 'Pedrosa', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 23, familyCode: '3.6', name: 'María Pilar', surname1: 'Rey-Stolle', surname2: 'Pedrosa', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 24, familyCode: '3.7', name: 'Ignacio', surname1: 'Rey-Stolle', surname2: 'Pedrosa', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 25, familyCode: '3.8', name: 'Francisco Javier', surname1: 'Rey-Stolle', surname2: 'Pedrosa', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 26, familyCode: '3.9', name: 'María Rosa', surname1: 'Rey-Stolle', surname2: 'de Imbert', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 27, familyCode: '3.10', name: 'María Teresa', surname1: 'Rey-Stolle', surname2: 'de Imbert', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 28, familyCode: '3.11', name: 'María Pilar', surname1: 'Rey-Stolle', surname2: 'de Imbert', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 29, familyCode: '3.12', name: 'José María', surname1: 'Rey-Stolle', surname2: 'de Imbert', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 30, familyCode: '3.13', name: 'María Antonia', surname1: 'Rey-Stolle', surname2: 'de Imbert', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 31, familyCode: '3.14', name: 'Juan Bosco', surname1: 'Rey-Stolle', surname2: 'de Imbert', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 32, familyCode: '3.15', name: 'Ana María', surname1: 'Rey-Stolle', surname2: 'de Imbert', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 },
  { id: 33, familyCode: '3.16', name: 'Luis Alfonso', surname1: 'Rey-Stolle', surname2: 'de Imbert', birthdate: 1842, deathdate: 1896, picture: 'assets/img/bosco.jpg', couple: true, offspring: 0 }
];